version: '3.8'

services:
  php-fpm:
    build:
      context: .
      dockerfile: php-fpm/Dockerfile
    container_name: php-fpm
    volumes:
      - ../app:/app

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ../app:/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params
    depends_on:
      - php-fpm

  db:
    image: mysql:8.0
    container_name: tictactoe-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: tictactoe
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf

volumes:
  db-data: